### ISSUE TITLE
Support for Complex Coeffecients/Evaluation

### ISSUE THREAD

**Issue by LordThunder333** [jannikmi/multivar_horner#37]
Is there any specific reason why the method cannot be implemented for complex coefficients or the polynomial cannot be evaluated at complex values?

**Comment by jannikmi** [comment]
Thanks for this feature request. I was not aware of any use case for this. I guess it would not be trivial to add this functionality, due to some assumptions for real numbers becoming invalid. Can you perhaps point to a reference implementation or example where I could understand the logic behind complex polynomial evaluation. Perhaps I can spot some similarities.

**Comment by jannikmi** [comment]
Not a problem. But what use case do you have in mind?

**Comment by LordThunder333** [comment]
I am a physicist. In my particular line of work, I must implement large multinomials (degree scaling with system size N and some other parameters), which must be evaluated about N^2 times. The multinomials are guaranteed to have real coefficients. However, the variables are generally all complex. I would like a horner-like method for these multinomials for efficient and accurate evaluation.

**Comment by jannikmi** [comment]
There are three different types of variables in this use case: exponents of the monomials, coefficients of the monomials and evaluation points of the polynomials. Which of them can be complex in your use case?

From the top of my head I don't know how complex variables would change the polynomial evaluation. Could you please reference an example calculation of how the evaluation is done in your complex use case? Then I could figure out how easy it would be to add this new functionality to the current implementation.

**Comment by jannikmi** [comment]
Side question for helping me to understand the algorithm: is there a trivial work around possible by evaluating the real and imaginary parts separately? If not what prohibits this? Complex multiplication?

**Comment by LordThunder333** [comment]
I see now. Only the evaluation points are complex. And as you say, I can't implement real and imaginary part calculations separately because of complex multiplication.

**Comment by jannikmi** [comment]
Ok, let me see what I can put together. Could you please provide test cases (coefficients, exponents, evaluation point, expected result)?

**Comment by jannikmi** [comment]
@LordThunder333 the basic functionality has been implemented in branch https://github.com/jannikmi/multivar_horner/pull/39
Check it out.

**Comment by jannikmi** [comment]
The version `5.1.0` includes the requested functionality. @LordThunder333 let me know if anything is missing.
